[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["python3 -m ensurepip --upgrade --break-system-packages", "cd backend && python3 -m pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
